### ISSUE TITLE
Create all-in-one client

### ISSUE THREAD

**Issue by crxdelsol** [jeffkreeftmeijer/UitzendingGemist#14]
The server should be dropped.
If you are beyond that part, you should consider throwing this application into the App Store. Instant fans since NPO doesn't do anything with it yet on the Apple TV 4.

Drop the remote JS files, and parse these directly in Swift 2.x within Xcode, that way everything will be done by the Apple TV 4, which does have way too much power for the current situation.

**Comment by jeffkreeftmeijer** [comment]
Users of this project need to side load it onto their devices, which is quite cumbersome. Instead of having everybody go through that again whenever something changes, the app is now automatically updated whenever something changes because the biggest part of the app is hosted on S3. 

As long as there's no plan to put this app in the app store, I think keeping the TVML templates and javascript files separate is the best idea. I'm closing this for now, please reopen if I'm missing something.
