### ISSUE TITLE
New available content

### ISSUE THREAD

**Issue by iAmRenzo** [jeffkreeftmeijer/UitzendingGemist#17]
Yesterday around 20:15 I wanted to see DWDD but I could not find it in this app. I went to UitzendingGemist on my SmartTV and there it was. How is content within this app refreshed? At intervals or anyother way? Can it be manually controlled (refresh button)?

**Comment by amphorainteractive** [comment]
You need to manually quit the app (double click home and swipe app to the top) and restart. I believe there already was an issue for this. 

gr,
nick

**Comment by jeffkreeftmeijer** [comment]
Yes, due to the way the views are stacked, the popular and recent views ware not reloaded whenever  they reappear, causing the content to become stale after a while. I'm closing this as there's an issue open for this already, but thanks for reporting, @iAmRenzo! 

@amphorainteractive thank you for commenting on this issue. As it generally takes me a while to find the time to go over these issues, your quick response is really appreciated.
