### ISSUE TITLE
Excessive loading times

### ISSUE THREAD

**Issue by basvroegop** [jeffkreeftmeijer/UitzendingGemist#6]
Some shows seem to have excessive loading times. Ran into this with all NOS Journaal I tried watching.

**Comment by urya** [comment]
To add to that: after clicking the menu button to go back from the loading screen, other shows are no longer clickable. Need to reboot the app.

**Comment by jeffkreeftmeijer** [comment]
Thanks for reporting, I've run into this before and it seems like there's something going wrong parsing JSON from the Uitzending Gemist API sometimes. After that, the app stops responding. 

As a first step, the app should probably display the error in an alert view, so the user can dismiss the alert and keep using the app instead of the whole thing breaking.

**Comment by jeffkreeftmeijer** [comment]
Step 1: I've added `createAlert()` to application.js (11abcd56fb85f236f206e2b64c332ceadab5fa88), so we can wrap places that cause the app to crash in `try`/`catch` blocks and open the alert instead of crashing like this:

    var alert = createAlert("uitzendinggemist.js", error);
    Presenter.removeLoadingIndicator();
    navigationDocument.presentModal(alert);

**Comment by jeffkreeftmeijer** [comment]
Step 2: I've added a `try` / `catch` block around the call to `JSON.parse()` in uitzendinggemist.js in 6ec6ddc8d54b3d692ceba4e26bbbc68cd6d05a4e, which I think will catch most errors users have been running into. Instead of becoming unusable, the app now shows the error in an alert.

Also, a94ef6454a74759033142e07eff8430499ee789c fixes an issue with (new) episodes that don't have an episode image (yet), which should greatly reduce the frequency of crashes like this.

**Comment by jeffkreeftmeijer** [comment]
I'm closing this one for now. Please reopen this issue if you run into problems like this again.
